run:
  tests: false

linters-settings:
  lll:
    line-length: 120
    tab-width: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - gas
    - gofmt
    - golint
    - gosimple
    - govet
    - lll
    - varcheck
    - unused

issues:
  exclude-use-default: false
